version: "2"
services:
  mysql:
    build: ./mysql
    image: dev-mysql # 为构建的image命名 repository_name:tag_name(可选)
    container_name: dev-mysql # 创建容器时的名称
    ports:
      - "3306:3306"
    volumes: # 挂载目录写这里
      - ./mount/data/mysql:/var/lib/mysql
      - ./mount/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    environment: # 自定义环境变量
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai

  redis:
    build: ./redis
    image: dev-redis
    container_name: dev-redis
    ports:
      - "6379:6379"
    volumes:
      - ./mount/data/redis:/data
    environment:
      TZ: Asia/Shanghai

  php:
    build: ./php
    image: dev-php
    container_name: dev-php
    ports:
      - "9000:9000"
    volumes:
      - ../website:/var/www/html
      - ./mount/conf/php.ini:/usr/local/etc/php/php.ini
    links:
      - "mysql" # service名称
      - "redis"
    environment:
      TZ: Asia/Shanghai

  nginx:
    build: ./nginx
    image: dev-nginx
    container_name: dev-nginx
    ports:
      - "80:80"
    volumes:
      - ../website:/usr/share/nginx/html
      - ./mount/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./mount/conf/vhosts.conf:/etc/nginx/conf.d/default.conf
      - ./mount/logs/nginx:/var/log/nginx
    links:
      - "php"
    environment:
      TZ: Asia/Shanghai
